apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- llm-processor
- nephio-bridge
- oran-adaptor
- rag-api
- ../../crds/nephoran.com_networkintents.yaml
- ../../crds/nephoran.com_managedelements.yaml
- ../../crds/nephoran.com_e2nodesets.yaml
- ../../../config/rbac/e2nodeset_admin.yaml
