apiVersion: nephoran.com/v1
kind: E2NodeSet
metadata:
  name: sample-e2nodeset
  namespace: default
spec:
  replicas: 3
---
apiVersion: nephoran.com/v1
kind: E2NodeSet
metadata:
  name: scaled-e2nodeset
  namespace: default
spec:
  replicas: 5
---
apiVersion: nephoran.com/v1
kind: E2NodeSet
metadata:
  name: custom-ric-e2nodeset
  namespace: default
spec:
  replicas: 2
  ricEndpoint: "https://custom-ric.example.com:9443"