apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- keda-installation.yaml
- scaledobjects.yaml
- keda-rbac.yaml

commonLabels:
  app.kubernetes.io/name: keda
  app.kubernetes.io/component: autoscaling
  app.kubernetes.io/part-of: nephoran-intent-operator